# Generated by Django 6.0.2 on 2026-03-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research_AI_Assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='model_used',
            field=models.CharField(blank=True, help_text='OpenRouter model used for LLM completion', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='used_default_model',
            field=models.BooleanField(default=True, help_text='Whether the default configured model was used on first attempt'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['used_default_model'], name='Research_AI_used_de_55b67b_idx'),
        ),
    ]
