# Generated by Django 6.0.2 on 2026-03-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Research_AI_Assistant', '0002_querylog_model_used_querylog_used_default_model_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='querylog',
            name='Research_AI_used_de_55b67b_idx',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='model_used',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='used_default_model',
        ),
    ]
